- hosts: ubuntu-test-vm

  vars_files:
    - secret

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
    
    - name: Install Tomcat 7
      become: true
      apt:
        name: tomcat7

    - name: Install Tomcat 7 tools
      become: true
      apt: name={{tomcat7_tools}}
      vars:
        tomcat7_tools:
          - tomcat7-docs
          - tomcat7-examples
          - tomcat7-admin

    - name: Copy tomcat7 config file
      become: true
      action: template src=../src/main/webapp/WEB-INF/tomcat7 dest=/etc/default/tomcat7
      notify: 
        - restart Tomcat 7

    - name: Copy tomcat-users config file
      become: true
      action: template src=../src/main/webapp/WEB-INF/tomcat-users.xml dest=/var/lib/tomcat7/conf/tomcat-users.xml
      notify: 
        - restart Tomcat 7

    - name: Copy server.xml config file
      become: true
      action: template src=../src/main/webapp/WEB-INF/server.xml dest=/var/lib/tomcat7/conf/server.xml
      notify: 
        - restart Tomcat 7

    - name: Start Tomcat 7 daemon
      become: true
      service:
        name: tomcat7
        state: started

    - name: Add user ubuntu to tomcat7 group
      become: true
      user: 
        name: ubuntu
        groups: tomcat7
        append: yes
  
  handlers:
    - name: restart Tomcat 7
      action: service name=tomcat7 state=restarted
